import 'package:flutter/material.dart';
import 'package:sensor_tree/Classes/Utils/resources/resources.dart';

final Map<String, Map<String, dynamic>> countryPhoneCodeMapping = {
  // LETTER: A
  'AF': {
    'countryName': 'Afghanistan',
    'phoneCode': '+93',
    'phoneLength': 9,
    'currency': 'AFN',
  },
  'AL': {
    'countryName': 'Albania',
    'phoneCode': '+355',
    'phoneLength': 9,
    'currency': 'ALL',
  },
  'DZ': {
    'countryName': 'Algeria',
    'phoneCode': '+213',
    'phoneLength': 9,
    'currency': 'DZD',
  },
  'AS': {
    'countryName': 'American Samoa',
    'phoneCode': '+1-684',
    'phoneLength': 7,
    'currency': 'USD',
  },
  'AD': {
    'countryName': 'Andorra',
    'phoneCode': '+376',
    'phoneLength': 6,
    'currency': 'EUR',
  },
  'AO': {
    'countryName': 'Angola',
    'phoneCode': '+244',
    'phoneLength': 9,
    'currency': 'AOA',
  },
  'AI': {
    'countryName': 'Anguilla',
    'phoneCode': '+1-264',
    'phoneLength': 7,
    'currency': 'XCD',
  },
  'AQ': {
    'countryName': 'Antarctica',
    'phoneCode': '+672',
    'phoneLength': 5,
    'currency': 'N/A',
  },
  'AG': {
    'countryName': 'Antigua and Barbuda',
    'phoneCode': '+1-268',
    'phoneLength': 7,
    'currency': 'XCD',
  },
  'AR': {
    'countryName': 'Argentina',
    'phoneCode': '+54',
    'phoneLength': 10,
    'currency': 'ARS',
  },
  'AM': {
    'countryName': 'Armenia',
    'phoneCode': '+374',
    'phoneLength': 8,
    'currency': 'AMD',
  },
  'AW': {
    'countryName': 'Aruba',
    'phoneCode': '+297',
    'phoneLength': 7,
    'currency': 'AWG',
  },
  'AU': {
    'countryName': 'Australia',
    'phoneCode': '+61',
    'phoneLength': 9,
    'currency': 'AUD',
  },
  'AT': {
    'countryName': 'Austria',
    'phoneCode': '+43',
    'phoneLength': 10,
    'currency': 'EUR',
  },
  'AZ': {
    'countryName': 'Azerbaijan',
    'phoneCode': '+994',
    'phoneLength': 9,
    'currency': 'AZN',
  },
  // LETTER: B
  'BS': {
    'countryName': 'Bahamas',
    'phoneCode': '+1-242',
    'phoneLength': 7,
    'currency': 'BSD',
  },
  'BH': {
    'countryName': 'Bahrain',
    'phoneCode': '+973',
    'phoneLength': 8,
    'currency': 'BHD',
  },
  'BD': {
    'countryName': 'Bangladesh',
    'phoneCode': '+880',
    'phoneLength': 10,
    'currency': 'BDT',
  },
  'BB': {
    'countryName': 'Barbados',
    'phoneCode': '+1-246',
    'phoneLength': 7,
    'currency': 'BBD',
  },
  'BY': {
    'countryName': 'Belarus',
    'phoneCode': '+375',
    'phoneLength': 9,
    'currency': 'BYN',
  },
  'BE': {
    'countryName': 'Belgium',
    'phoneCode': '+32',
    'phoneLength': 9,
    'currency': 'EUR',
  },
  'BZ': {
    'countryName': 'Belize',
    'phoneCode': '+501',
    'phoneLength': 7,
    'currency': 'BZD',
  },
  'BJ': {
    'countryName': 'Benin',
    'phoneCode': '+229',
    'phoneLength': 8,
    'currency': 'XOF',
  },
  'BM': {
    'countryName': 'Bermuda',
    'phoneCode': '+1-441',
    'phoneLength': 7,
    'currency': 'BMD',
  },
  'BT': {
    'countryName': 'Bhutan',
    'phoneCode': '+975',
    'phoneLength': 8,
    'currency': 'BTN',
  },
  'BO': {
    'countryName': 'Bolivia',
    'phoneCode': '+591',
    'phoneLength': 8,
    'currency': 'BOB',
  },
  'BA': {
    'countryName': 'Bosnia and Herzegovina',
    'phoneCode': '+387',
    'phoneLength': 8,
    'currency': 'BAM',
  },
  'BW': {
    'countryName': 'Botswana',
    'phoneCode': '+267',
    'phoneLength': 8,
    'currency': 'BWP',
  },
  'BR': {
    'countryName': 'Brazil',
    'phoneCode': '+55',
    'phoneLength': 11,
    'currency': 'BRL',
  },
  'IO': {
    'countryName': 'British Indian Ocean Territory',
    'phoneCode': '+246',
    'phoneLength': 7,
    'currency': 'USD',
  },
  'VG': {
    'countryName': 'British Virgin Islands',
    'phoneCode': '+1-284',
    'phoneLength': 7,
    'currency': 'USD',
  },
  'BN': {
    'countryName': 'Brunei',
    'phoneCode': '+673',
    'phoneLength': 7,
    'currency': 'BND',
  },
  'BG': {
    'countryName': 'Bulgaria',
    'phoneCode': '+359',
    'phoneLength': 9,
    'currency': 'BGN',
  },
  'BF': {
    'countryName': 'Burkina Faso',
    'phoneCode': '+226',
    'phoneLength': 8,
    'currency': 'XOF',
  },
  'BI': {
    'countryName': 'Burundi',
    'phoneCode': '+257',
    'phoneLength': 8,
    'currency': 'BIF',
  },
  // letter C
  'KH': {
    'countryName': 'Cambodia',
    'phoneCode': '+855',
    'phoneLength': 9,
    'currency': 'KHR',
  },
  'CM': {
    'countryName': 'Cameroon',
    'phoneCode': '+237',
    'phoneLength': 9,
    'currency': 'XAF',
  },
  'CA': {
    'countryName': 'Canada',
    'phoneCode': '+1',
    'phoneLength': 10,
    'currency': 'CAD',
  },
  'CV': {
    'countryName': 'Cape Verde',
    'phoneCode': '+238',
    'phoneLength': 7,
    'currency': 'CVE',
  },
  'KY': {
    'countryName': 'Cayman Islands',
    'phoneCode': '+1-345',
    'phoneLength': 7,
    'currency': 'KYD',
  },
  'CF': {
    'countryName': 'Central African Republic',
    'phoneCode': '+236',
    'phoneLength': 8,
    'currency': 'XAF',
  },
  'TD': {
    'countryName': 'Chad',
    'phoneCode': '+235',
    'phoneLength': 8,
    'currency': 'XAF',
  },
  'CL': {
    'countryName': 'Chile',
    'phoneCode': '+56',
    'phoneLength': 9,
    'currency': 'CLP',
  },
  'CN': {
    'countryName': 'China',
    'phoneCode': '+86',
    'phoneLength': 11,
    'currency': 'CNY',
  },
  'CX': {
    'countryName': 'Christmas Island',
    'phoneCode': '+61',
    'phoneLength': 6,
    'currency': 'AUD',
  },
  'CC': {
    'countryName': 'Cocos (Keeling) Islands',
    'phoneCode': '+61',
    'phoneLength': 6,
    'currency': 'AUD',
  },
  'CO': {
    'countryName': 'Colombia',
    'phoneCode': '+57',
    'phoneLength': 10,
    'currency': 'COP',
  },
  'KM': {
    'countryName': 'Comoros',
    'phoneCode': '+269',
    'phoneLength': 7,
    'currency': 'KMF',
  },
  'CG': {
    'countryName': 'Congo',
    'phoneCode': '+242',
    'phoneLength': 9,
    'currency': 'XAF',
  },
  'CD': {
    'countryName': 'Democratic Republic of the Congo',
    'phoneCode': '+243',
    'phoneLength': 9,
    'currency': 'CDF',
  },
  'CK': {
    'countryName': 'Cook Islands',
    'phoneCode': '+682',
    'phoneLength': 5,
    'currency': 'NZD',
  },
  'CR': {
    'countryName': 'Costa Rica',
    'phoneCode': '+506',
    'phoneLength': 8,
    'currency': 'CRC',
  },
  'CI': {
    'countryName': 'Côte d\'Ivoire',
    'phoneCode': '+225',
    'phoneLength': 8,
    'currency': 'XOF',
  },
  'HR': {
    'countryName': 'Croatia',
    'phoneCode': '+385',
    'phoneLength': 9,
    'currency': 'EUR',
  },
  'CU': {
    'countryName': 'Cuba',
    'phoneCode': '+53',
    'phoneLength': 8,
    'currency': 'CUP',
  },
  'CW': {
    'countryName': 'Curaçao',
    'phoneCode': '+599',
    'phoneLength': 7,
    'currency': 'ANG',
  },
  'CY': {
    'countryName': 'Cyprus',
    'phoneCode': '+357',
    'phoneLength': 8,
    'currency': 'EUR',
  },
  'CZ': {
    'countryName': 'Czech Republic',
    'phoneCode': '+420',
    'phoneLength': 9,
    'currency': 'CZK',
  },
  // letter D
  'DK': {
    'countryName': 'Denmark',
    'phoneCode': '+45',
    'phoneLength': 8,
    'currency': 'DKK',
  },
  'DJ': {
    'countryName': 'Djibouti',
    'phoneCode': '+253',
    'phoneLength': 6,
    'currency': 'DJF',
  },
  'DM': {
    'countryName': 'Dominica',
    'phoneCode': '+1-767',
    'phoneLength': 7,
    'currency': 'XCD',
  },
  'DO': {
    'countryName': 'Dominican Republic',
    'phoneCode': '+1-809',
    'phoneLength': 10,
    'currency': 'DOP',
  },
  // 'DZ': {'countryName': 'Algeria', 'phoneCode': '+213', 'phoneLength': 9, 'currency': 'DZD'}
  // letter E
  'EC': {
    'countryName': 'Ecuador',
    'phoneCode': '+593',
    'phoneLength': 9,
    'currency': 'USD',
  },
  'EG': {
    'countryName': 'Egypt',
    'phoneCode': '+20',
    'phoneLength': 10,
    'currency': 'EGP',
  },
  'SV': {
    'countryName': 'El Salvador',
    'phoneCode': '+503',
    'phoneLength': 8,
    'currency': 'USD',
  },
  'GQ': {
    'countryName': 'Equatorial Guinea',
    'phoneCode': '+240',
    'phoneLength': 9,
    'currency': 'XAF',
  },
  'ER': {
    'countryName': 'Eritrea',
    'phoneCode': '+291',
    'phoneLength': 7,
    'currency': 'ERN',
  },
  'EE': {
    'countryName': 'Estonia',
    'phoneCode': '+372',
    'phoneLength': 8,
    'currency': 'EUR',
  },
  'SZ': {
    'countryName': 'Eswatini',
    'phoneCode': '+268',
    'phoneLength': 8,
    'currency': 'SZL',
  },
  'ET': {
    'countryName': 'Ethiopia',
    'phoneCode': '+251',
    'phoneLength': 9,
    'currency': 'ETB',
  },
  // letter F
  'FK': {
    'countryName': 'Falkland Islands',
    'phoneCode': '+500',
    'phoneLength': 5,
    'currency': 'FKP',
  },
  'FO': {
    'countryName': 'Faroe Islands',
    'phoneCode': '+298',
    'phoneLength': 6,
    'currency': 'DKK',
  },
  'FJ': {
    'countryName': 'Fiji',
    'phoneCode': '+679',
    'phoneLength': 7,
    'currency': 'FJD',
  },
  'FI': {
    'countryName': 'Finland',
    'phoneCode': '+358',
    'phoneLength': 10,
    'currency': 'EUR',
  },
  'FR': {
    'countryName': 'France',
    'phoneCode': '+33',
    'phoneLength': 9,
    'currency': 'EUR',
  },
  // letter G
  'GA': {
    'countryName': 'Gabon',
    'phoneCode': '+241',
    'phoneLength': 9,
    'currency': 'XAF',
  },
  'GM': {
    'countryName': 'Gambia',
    'phoneCode': '+220',
    'phoneLength': 7,
    'currency': 'GMD',
  },
  'GE': {
    'countryName': 'Georgia',
    'phoneCode': '+995',
    'phoneLength': 9,
    'currency': 'GEL',
  },
  'DE': {
    'countryName': 'Germany',
    'phoneCode': '+49',
    'phoneLength': 10,
    'currency': 'EUR',
  },
  'GH': {
    'countryName': 'Ghana',
    'phoneCode': '+233',
    'phoneLength': 10,
    'currency': 'GHS',
  },
  'GI': {
    'countryName': 'Gibraltar',
    'phoneCode': '+350',
    'phoneLength': 8,
    'currency': 'GIP',
  },
  'GR': {
    'countryName': 'Greece',
    'phoneCode': '+30',
    'phoneLength': 10,
    'currency': 'EUR',
  },
  'GL': {
    'countryName': 'Greenland',
    'phoneCode': '+299',
    'phoneLength': 6,
    'currency': 'DKK',
  },
  'GD': {
    'countryName': 'Grenada',
    'phoneCode': '+1-473',
    'phoneLength': 7,
    'currency': 'XCD',
  },
  'GU': {
    'countryName': 'Guam',
    'phoneCode': '+1-671',
    'phoneLength': 7,
    'currency': 'USD',
  },
  'GT': {
    'countryName': 'Guatemala',
    'phoneCode': '+502',
    'phoneLength': 8,
    'currency': 'GTQ',
  },
  'GG': {
    'countryName': 'Guernsey',
    'phoneCode': '+44-1481',
    'phoneLength': 10,
    'currency': 'GBP',
  },
  'GN': {
    'countryName': 'Guinea',
    'phoneCode': '+224',
    'phoneLength': 9,
    'currency': 'GNF',
  },
  'GW': {
    'countryName': 'Guinea-Bissau',
    'phoneCode': '+245',
    'phoneLength': 7,
    'currency': 'XOF',
  },
  'GY': {
    'countryName': 'Guyana',
    'phoneCode': '+592',
    'phoneLength': 7,
    'currency': 'GYD',
  },
  // letter H
  'HT': {
    'countryName': 'Haiti',
    'phoneCode': '+509',
    'phoneLength': 8,
    'currency': 'HTG',
  },
  'HN': {
    'countryName': 'Honduras',
    'phoneCode': '+504',
    'phoneLength': 8,
    'currency': 'HNL',
  },
  'HK': {
    'countryName': 'Hong Kong',
    'phoneCode': '+852',
    'phoneLength': 8,
    'currency': 'HKD',
  },
  'HU': {
    'countryName': 'Hungary',
    'phoneCode': '+36',
    'phoneLength': 9,
    'currency': 'HUF',
  },
  // letter I
  'IS': {
    'countryName': 'Iceland',
    'phoneCode': '+354',
    'phoneLength': 7,
    'currency': 'ISK',
  },
  'IN': {
    'countryName': 'India',
    'phoneCode': '+91',
    'phoneLength': 10,
    'currency': 'INR',
  },
  'ID': {
    'countryName': 'Indonesia',
    'phoneCode': '+62',
    'phoneLength': 10,
    'currency': 'IDR',
  },
  'IR': {
    'countryName': 'Iran',
    'phoneCode': '+98',
    'phoneLength': 10,
    'currency': 'IRR',
  },
  'IQ': {
    'countryName': 'Iraq',
    'phoneCode': '+964',
    'phoneLength': 10,
    'currency': 'IQD',
  },
  'IE': {
    'countryName': 'Ireland',
    'phoneCode': '+353',
    'phoneLength': 9,
    'currency': 'EUR',
  },
  'IM': {
    'countryName': 'Isle of Man',
    'phoneCode': '+44-1624',
    'phoneLength': 10,
    'currency': 'GBP',
  },
  'IL': {
    'countryName': 'Israel',
    'phoneCode': '+972',
    'phoneLength': 9,
    'currency': 'ILS',
  },
  'IT': {
    'countryName': 'Italy',
    'phoneCode': '+39',
    'phoneLength': 10,
    'currency': 'EUR',
  },
  // letter J
  'JM': {
    'countryName': 'Jamaica',
    'phoneCode': '+1-876',
    'phoneLength': 7,
    'currency': 'JMD',
  },
  'JP': {
    'countryName': 'Japan',
    'phoneCode': '+81',
    'phoneLength': 10,
    'currency': 'JPY',
  },
  'JE': {
    'countryName': 'Jersey',
    'phoneCode': '+44-1534',
    'phoneLength': 10,
    'currency': 'GBP',
  },
  'JO': {
    'countryName': 'Jordan',
    'phoneCode': '+962',
    'phoneLength': 9,
    'currency': 'JOD',
  },
  // letter K
  'KZ': {
    'countryName': 'Kazakhstan',
    'phoneCode': '+7',
    'phoneLength': 10,
    'currency': 'KZT',
  },
  'KE': {
    'countryName': 'Kenya',
    'phoneCode': '+254',
    'phoneLength': 10,
    'currency': 'KES',
  },
  'KI': {
    'countryName': 'Kiribati',
    'phoneCode': '+686',
    'phoneLength': 8,
    'currency': 'AUD',
  },
  'KP': {
    'countryName': 'North Korea',
    'phoneCode': '+850',
    'phoneLength': 8,
    'currency': 'KPW',
  },
  'KR': {
    'countryName': 'South Korea',
    'phoneCode': '+82',
    'phoneLength': 10,
    'currency': 'KRW',
  },
  'KW': {
    'countryName': 'Kuwait',
    'phoneCode': '+965',
    'phoneLength': 8,
    'currency': 'KWD',
  },
  'KG': {
    'countryName': 'Kyrgyzstan',
    'phoneCode': '+996',
    'phoneLength': 9,
    'currency': 'KGS',
  },
  // letter L
  'LA': {
    'countryName': 'Laos',
    'phoneCode': '+856',
    'phoneLength': 9,
    'currency': 'LAK',
  },
  'LV': {
    'countryName': 'Latvia',
    'phoneCode': '+371',
    'phoneLength': 8,
    'currency': 'EUR',
  },
  'LB': {
    'countryName': 'Lebanon',
    'phoneCode': '+961',
    'phoneLength': 8,
    'currency': 'LBP',
  },
  'LS': {
    'countryName': 'Lesotho',
    'phoneCode': '+266',
    'phoneLength': 8,
    'currency': 'LSL',
  },
  'LR': {
    'countryName': 'Liberia',
    'phoneCode': '+231',
    'phoneLength': 7,
    'currency': 'LRD',
  },
  'LY': {
    'countryName': 'Libya',
    'phoneCode': '+218',
    'phoneLength': 9,
    'currency': 'LYD',
  },
  'LI': {
    'countryName': 'Liechtenstein',
    'phoneCode': '+423',
    'phoneLength': 7,
    'currency': 'CHF',
  },
  'LT': {
    'countryName': 'Lithuania',
    'phoneCode': '+370',
    'phoneLength': 8,
    'currency': 'EUR',
  },
  'LU': {
    'countryName': 'Luxembourg',
    'phoneCode': '+352',
    'phoneLength': 9,
    'currency': 'EUR',
  },
  // letter M
  'MG': {
    'countryName': 'Madagascar',
    'phoneCode': '+261',
    'phoneLength': 9,
    'currency': 'MGA',
  },
  'MW': {
    'countryName': 'Malawi',
    'phoneCode': '+265',
    'phoneLength': 9,
    'currency': 'MWK',
  },
  'MY': {
    'countryName': 'Malaysia',
    'phoneCode': '+60',
    'phoneLength': 10,
    'currency': 'MYR',
  },
  'MV': {
    'countryName': 'Maldives',
    'phoneCode': '+960',
    'phoneLength': 7,
    'currency': 'MVR',
  },
  'ML': {
    'countryName': 'Mali',
    'phoneCode': '+223',
    'phoneLength': 8,
    'currency': 'XOF',
  },
  'MT': {
    'countryName': 'Malta',
    'phoneCode': '+356',
    'phoneLength': 8,
    'currency': 'EUR',
  },
  'MH': {
    'countryName': 'Marshall Islands',
    'phoneCode': '+692',
    'phoneLength': 7,
    'currency': 'USD',
  },
  'MR': {
    'countryName': 'Mauritania',
    'phoneCode': '+222',
    'phoneLength': 8,
    'currency': 'MRU',
  },
  'MU': {
    'countryName': 'Mauritius',
    'phoneCode': '+230',
    'phoneLength': 8,
    'currency': 'MUR',
  },
  'MX': {
    'countryName': 'Mexico',
    'phoneCode': '+52',
    'phoneLength': 10,
    'currency': 'MXN',
  },
  'FM': {
    'countryName': 'Micronesia',
    'phoneCode': '+691',
    'phoneLength': 7,
    'currency': 'USD',
  },
  'MD': {
    'countryName': 'Moldova',
    'phoneCode': '+373',
    'phoneLength': 8,
    'currency': 'MDL',
  },
  'MC': {
    'countryName': 'Monaco',
    'phoneCode': '+377',
    'phoneLength': 9,
    'currency': 'EUR',
  },
  'MN': {
    'countryName': 'Mongolia',
    'phoneCode': '+976',
    'phoneLength': 8,
    'currency': 'MNT',
  },
  'ME': {
    'countryName': 'Montenegro',
    'phoneCode': '+382',
    'phoneLength': 8,
    'currency': 'EUR',
  },
  'MA': {
    'countryName': 'Morocco',
    'phoneCode': '+212',
    'phoneLength': 9,
    'currency': 'MAD',
  },
  'MZ': {
    'countryName': 'Mozambique',
    'phoneCode': '+258',
    'phoneLength': 9,
    'currency': 'MZN',
  },
  'MM': {
    'countryName': 'Myanmar',
    'phoneCode': '+95',
    'phoneLength': 9,
    'currency': 'MMK',
  },
  // letter N
  'NA': {
    'countryName': 'Namibia',
    'phoneCode': '+264',
    'phoneLength': 9,
    'currency': 'NAD',
  },
  'NR': {
    'countryName': 'Nauru',
    'phoneCode': '+674',
    'phoneLength': 7,
    'currency': 'AUD',
  },
  'NP': {
    'countryName': 'Nepal',
    'phoneCode': '+977',
    'phoneLength': 10,
    'currency': 'NPR',
  },
  'NL': {
    'countryName': 'Netherlands',
    'phoneCode': '+31',
    'phoneLength': 9,
    'currency': 'EUR',
  },
  'NZ': {
    'countryName': 'New Zealand',
    'phoneCode': '+64',
    'phoneLength': 9,
    'currency': 'NZD',
  },
  'NI': {
    'countryName': 'Nicaragua',
    'phoneCode': '+505',
    'phoneLength': 8,
    'currency': 'NIO',
  },
  'NE': {
    'countryName': 'Niger',
    'phoneCode': '+227',
    'phoneLength': 8,
    'currency': 'XOF',
  },
  'NG': {
    'countryName': 'Nigeria',
    'phoneCode': '+234',
    'phoneLength': 10,
    'currency': 'NGN',
  },
  'NU': {
    'countryName': 'Niue',
    'phoneCode': '+683',
    'phoneLength': 4,
    'currency': 'NZD',
  },
  'NF': {
    'countryName': 'Norfolk Island',
    'phoneCode': '+672',
    'phoneLength': 6,
    'currency': 'AUD',
  },
  // 'KP': {'countryName': 'North Korea', 'phoneCode': '+850', 'phoneLength': 8, 'currency': 'KPW'},
  'MK': {
    'countryName': 'North Macedonia',
    'phoneCode': '+389',
    'phoneLength': 8,
    'currency': 'MKD',
  },
  'NO': {
    'countryName': 'Norway',
    'phoneCode': '+47',
    'phoneLength': 8,
    'currency': 'NOK',
  },
  // letter O
  'OM': {
    'countryName': 'Oman',
    'phoneCode': '+968',
    'phoneLength': 8,
    'currency': 'OMR',
  },
  // letter P
  'PW': {
    'countryName': 'Palau',
    'phoneCode': '+680',
    'phoneLength': 7,
    'currency': 'USD',
  },
  'PS': {
    'countryName': 'Palestine',
    'phoneCode': '+970',
    'phoneLength': 9,
    'currency': 'ILS',
  },
  'PA': {
    'countryName': 'Panama',
    'phoneCode': '+507',
    'phoneLength': 8,
    'currency': 'PAB',
  },
  'PG': {
    'countryName': 'Papua New Guinea',
    'phoneCode': '+675',
    'phoneLength': 8,
    'currency': 'PGK',
  },
  'PY': {
    'countryName': 'Paraguay',
    'phoneCode': '+595',
    'phoneLength': 9,
    'currency': 'PYG',
  },
  'PE': {
    'countryName': 'Peru',
    'phoneCode': '+51',
    'phoneLength': 9,
    'currency': 'PEN',
  },
  'PH': {
    'countryName': 'Philippines',
    'phoneCode': '+63',
    'phoneLength': 10,
    'currency': 'PHP',
  },
  'PL': {
    'countryName': 'Poland',
    'phoneCode': '+48',
    'phoneLength': 9,
    'currency': 'PLN',
  },
  'PT': {
    'countryName': 'Portugal',
    'phoneCode': '+351',
    'phoneLength': 9,
    'currency': 'EUR',
  },
  'PR': {
    'countryName': 'Puerto Rico',
    'phoneCode': '+1-787',
    'phoneLength': 10,
    'currency': 'USD',
  },
  // letter Q
  'QA': {
    'countryName': 'Qatar',
    'phoneCode': '+974',
    'phoneLength': 8,
    'currency': 'QAR',
  },
  // letter R
  'RE': {
    'countryName': 'Réunion',
    'phoneCode': '+262',
    'phoneLength': 9,
    'currency': 'EUR',
  },
  'RO': {
    'countryName': 'Romania',
    'phoneCode': '+40',
    'phoneLength': 9,
    'currency': 'RON',
  },
  'RU': {
    'countryName': 'Russia',
    'phoneCode': '+7',
    'phoneLength': 10,
    'currency': 'RUB',
  },
  'RW': {
    'countryName': 'Rwanda',
    'phoneCode': '+250',
    'phoneLength': 9,
    'currency': 'RWF',
  },
  // letter S
  'WS': {
    'countryName': 'Samoa',
    'phoneCode': '+685',
    'phoneLength': 7,
    'currency': 'WST',
  },
  'SM': {
    'countryName': 'San Marino',
    'phoneCode': '+378',
    'phoneLength': 9,
    'currency': 'EUR',
  },
  'ST': {
    'countryName': 'Sao Tome and Principe',
    'phoneCode': '+239',
    'phoneLength': 7,
    'currency': 'STN',
  },
  'SA': {
    'countryName': 'Saudi Arabia',
    'phoneCode': '+966',
    'phoneLength': 9,
    'currency': 'SAR',
  },
  'SN': {
    'countryName': 'Senegal',
    'phoneCode': '+221',
    'phoneLength': 9,
    'currency': 'XOF',
  },
  'RS': {
    'countryName': 'Serbia',
    'phoneCode': '+381',
    'phoneLength': 9,
    'currency': 'RSD',
  },
  'SC': {
    'countryName': 'Seychelles',
    'phoneCode': '+248',
    'phoneLength': 7,
    'currency': 'SCR',
  },
  'SL': {
    'countryName': 'Sierra Leone',
    'phoneCode': '+232',
    'phoneLength': 8,
    'currency': 'SLL',
  },
  'SG': {
    'countryName': 'Singapore',
    'phoneCode': '+65',
    'phoneLength': 8,
    'currency': 'SGD',
  },
  'SK': {
    'countryName': 'Slovakia',
    'phoneCode': '+421',
    'phoneLength': 9,
    'currency': 'EUR',
  },
  'SI': {
    'countryName': 'Slovenia',
    'phoneCode': '+386',
    'phoneLength': 9,
    'currency': 'EUR',
  },
  'SB': {
    'countryName': 'Solomon Islands',
    'phoneCode': '+677',
    'phoneLength': 7,
    'currency': 'SBD',
  },
  'SO': {
    'countryName': 'Somalia',
    'phoneCode': '+252',
    'phoneLength': 9,
    'currency': 'SOS',
  },
  'ZA': {
    'countryName': 'South Africa',
    'phoneCode': '+27',
    'phoneLength': 9,
    'currency': 'ZAR',
  },
  'ES': {
    'countryName': 'Spain',
    'phoneCode': '+34',
    'phoneLength': 9,
    'currency': 'EUR',
  },
  'LK': {
    'countryName': 'Sri Lanka',
    'phoneCode': '+94',
    'phoneLength': 9,
    'currency': 'LKR',
  },
  'SD': {
    'countryName': 'Sudan',
    'phoneCode': '+249',
    'phoneLength': 9,
    'currency': 'SDG',
  },
  'SR': {
    'countryName': 'Suriname',
    'phoneCode': '+597',
    'phoneLength': 7,
    'currency': 'SRD',
  },
  'SE': {
    'countryName': 'Sweden',
    'phoneCode': '+46',
    'phoneLength': 9,
    'currency': 'SEK',
  },
  'CH': {
    'countryName': 'Switzerland',
    'phoneCode': '+41',
    'phoneLength': 9,
    'currency': 'CHF',
  },
  'SY': {
    'countryName': 'Syria',
    'phoneCode': '+963',
    'phoneLength': 9,
    'currency': 'SYP',
  },
  // letter T
  'TW': {
    'countryName': 'Taiwan',
    'phoneCode': '+886',
    'phoneLength': 9,
    'currency': 'TWD',
  },
  'TJ': {
    'countryName': 'Tajikistan',
    'phoneCode': '+992',
    'phoneLength': 9,
    'currency': 'TJS',
  },
  'TZ': {
    'countryName': 'Tanzania',
    'phoneCode': '+255',
    'phoneLength': 9,
    'currency': 'TZS',
  },
  'TH': {
    'countryName': 'Thailand',
    'phoneCode': '+66',
    'phoneLength': 9,
    'currency': 'THB',
  },
  'TG': {
    'countryName': 'Togo',
    'phoneCode': '+228',
    'phoneLength': 8,
    'currency': 'XOF',
  },
  'TO': {
    'countryName': 'Tonga',
    'phoneCode': '+676',
    'phoneLength': 5,
    'currency': 'TOP',
  },
  'TT': {
    'countryName': 'Trinidad and Tobago',
    'phoneCode': '+1-868',
    'phoneLength': 7,
    'currency': 'TTD',
  },
  'TN': {
    'countryName': 'Tunisia',
    'phoneCode': '+216',
    'phoneLength': 8,
    'currency': 'TND',
  },
  'TR': {
    'countryName': 'Turkey',
    'phoneCode': '+90',
    'phoneLength': 10,
    'currency': 'TRY',
  },
  'TM': {
    'countryName': 'Turkmenistan',
    'phoneCode': '+993',
    'phoneLength': 8,
    'currency': 'TMT',
  },
  'TV': {
    'countryName': 'Tuvalu',
    'phoneCode': '+688',
    'phoneLength': 5,
    'currency': 'AUD',
  },
  // letter U
  'UG': {
    'countryName': 'Uganda',
    'phoneCode': '+256',
    'phoneLength': 9,
    'currency': 'UGX',
  },
  'UA': {
    'countryName': 'Ukraine',
    'phoneCode': '+380',
    'phoneLength': 9,
    'currency': 'UAH',
  },
  'AE': {
    'countryName': 'United Arab Emirates',
    'phoneCode': '+971',
    'phoneLength': 9,
    'currency': 'AED',
  },
  'GB': {
    'countryName': 'United Kingdom',
    'phoneCode': '+44',
    'phoneLength': 10,
    'currency': 'GBP',
  },
  'US': {
    'countryName': 'United States',
    'phoneCode': '+1',
    'phoneLength': 10,
    'currency': 'USD',
  },
  'UY': {
    'countryName': 'Uruguay',
    'phoneCode': '+598',
    'phoneLength': 9,
    'currency': 'UYU',
  },
  'UZ': {
    'countryName': 'Uzbekistan',
    'phoneCode': '+998',
    'phoneLength': 9,
    'currency': 'UZS',
  },
  // letter V
  'VU': {
    'countryName': 'Vanuatu',
    'phoneCode': '+678',
    'phoneLength': 7,
    'currency': 'VUV',
  },
  'VA': {
    'countryName': 'Vatican City',
    'phoneCode': '+379',
    'phoneLength': 9,
    'currency': 'EUR',
  },
  'VE': {
    'countryName': 'Venezuela',
    'phoneCode': '+58',
    'phoneLength': 10,
    'currency': 'VES',
  },
  'VN': {
    'countryName': 'Vietnam',
    'phoneCode': '+84',
    'phoneLength': 9,
    'currency': 'VND',
  },
  // letter W
  'WF': {
    'countryName': 'Wallis and Futuna',
    'phoneCode': '+681',
    'phoneLength': 6,
    'currency': 'XPF',
  },
  'EH': {
    'countryName': 'Western Sahara',
    'phoneCode': '+212',
    'phoneLength': 9,
    'currency': 'MAD',
  },
  // letter X
  // letter Y
  'YE': {
    'countryName': 'Yemen',
    'phoneCode': '+967',
    'phoneLength': 9,
    'currency': 'YER',
  },
  // letter Z
  'ZM': {
    'countryName': 'Zambia',
    'phoneCode': '+260',
    'phoneLength': 9,
    'currency': 'ZMW',
  },
  'ZW': {
    'countryName': 'Zimbabwe',
    'phoneCode': '+263',
    'phoneLength': 9,
    'currency': 'ZWL',
  },
  /*'AF': {'countryName': 'Afghanistan', 'phoneCode': '+93', 'phoneLength': 9},
  'AL': {'countryName': 'Albania', 'phoneCode': '+355', 'phoneLength': 9},
  'DZ': {'countryName': 'Algeria', 'phoneCode': '+213', 'phoneLength': 9},
  'AD': {'countryName': 'Andorra', 'phoneCode': '+376', 'phoneLength': 6},
  'AO': {'countryName': 'Angola', 'phoneCode': '+244', 'phoneLength': 9},
  'AR': {'countryName': 'Argentina', 'phoneCode': '+54', 'phoneLength': 10},
  'AM': {'countryName': 'Armenia', 'phoneCode': '+374', 'phoneLength': 8},
  'AU': {'countryName': 'Australia', 'phoneCode': '+61', 'phoneLength': 9},
  'AT': {'countryName': 'Austria', 'phoneCode': '+43', 'phoneLength': 10},
  'AZ': {'countryName': 'Azerbaijan', 'phoneCode': '+994', 'phoneLength': 9},
  'BH': {'countryName': 'Bahrain', 'phoneCode': '+973', 'phoneLength': 8},
  'BD': {'countryName': 'Bangladesh', 'phoneCode': '+880', 'phoneLength': 10},
  'BY': {'countryName': 'Belarus', 'phoneCode': '+375', 'phoneLength': 9},
  'BE': {'countryName': 'Belgium', 'phoneCode': '+32', 'phoneLength': 9},
  'BZ': {'countryName': 'Belize', 'phoneCode': '+501', 'phoneLength': 7},
  'BJ': {'countryName': 'Benin', 'phoneCode': '+229', 'phoneLength': 8},
  'BT': {'countryName': 'Bhutan', 'phoneCode': '+975', 'phoneLength': 8},
  'BO': {'countryName': 'Bolivia', 'phoneCode': '+591', 'phoneLength': 8},
  'BA': {
    'countryName': 'Bosnia and Herzegovina',
    'phoneCode': '+387',
    'phoneLength': 8,
  },
  'BW': {'countryName': 'Botswana', 'phoneCode': '+267', 'phoneLength': 8},
  'BR': {'countryName': 'Brazil', 'phoneCode': '+55', 'phoneLength': 11},
  'BN': {'countryName': 'Brunei', 'phoneCode': '+673', 'phoneLength': 7},
  'BG': {'countryName': 'Bulgaria', 'phoneCode': '+359', 'phoneLength': 9},
  'BF': {'countryName': 'Burkina Faso', 'phoneCode': '+226', 'phoneLength': 8},
  'BI': {'countryName': 'Burundi', 'phoneCode': '+257', 'phoneLength': 8},
  'KH': {'countryName': 'Cambodia', 'phoneCode': '+855', 'phoneLength': 9},
  'CM': {'countryName': 'Cameroon', 'phoneCode': '+237', 'phoneLength': 9},
  'CA': {'countryName': 'Canada', 'phoneCode': '+1', 'phoneLength': 10},
  'CV': {'countryName': 'Cape Verde', 'phoneCode': '+238', 'phoneLength': 7},
  'CF': {
    'countryName': 'Central African Republic',
    'phoneCode': '+236',
    'phoneLength': 8,
  },
  'TD': {'countryName': 'Chad', 'phoneCode': '+235', 'phoneLength': 8},
  'CL': {'countryName': 'Chile', 'phoneCode': '+56', 'phoneLength': 9},
  'CN': {'countryName': 'China', 'phoneCode': '+86', 'phoneLength': 11},
  'CO': {'countryName': 'Colombia', 'phoneCode': '+57', 'phoneLength': 10},
  'KM': {'countryName': 'Comoros', 'phoneCode': '+269', 'phoneLength': 7},
  'CG': {'countryName': 'Congo', 'phoneCode': '+242', 'phoneLength': 9},
  'CR': {'countryName': 'Costa Rica', 'phoneCode': '+506', 'phoneLength': 8},
  'HR': {'countryName': 'Croatia', 'phoneCode': '+385', 'phoneLength': 9},
  'CU': {'countryName': 'Cuba', 'phoneCode': '+53', 'phoneLength': 8},
  'CY': {'countryName': 'Cyprus', 'phoneCode': '+357', 'phoneLength': 8},
  'CZ': {
    'countryName': 'Czech Republic',
    'phoneCode': '+420',
    'phoneLength': 9,
  },
  'DK': {'countryName': 'Denmark', 'phoneCode': '+45', 'phoneLength': 8},
  'DJ': {'countryName': 'Djibouti', 'phoneCode': '+253', 'phoneLength': 6},
  'DM': {'countryName': 'Dominica', 'phoneCode': '+1-767', 'phoneLength': 7},
  'DO': {
    'countryName': 'Dominican Republic',
    'phoneCode': '+1-809',
    'phoneLength': 10,
  },
  'EC': {'countryName': 'Ecuador', 'phoneCode': '+593', 'phoneLength': 9},
  'EG': {'countryName': 'Egypt', 'phoneCode': '+20', 'phoneLength': 10},
  'SV': {'countryName': 'El Salvador', 'phoneCode': '+503', 'phoneLength': 8},
  'GQ': {
    'countryName': 'Equatorial Guinea',
    'phoneCode': '+240',
    'phoneLength': 9,
  },
  'ER': {'countryName': 'Eritrea', 'phoneCode': '+291', 'phoneLength': 7},
  'EE': {'countryName': 'Estonia', 'phoneCode': '+372', 'phoneLength': 8},
  'ET': {'countryName': 'Ethiopia', 'phoneCode': '+251', 'phoneLength': 9},
  'FI': {'countryName': 'Finland', 'phoneCode': '+358', 'phoneLength': 10},
  'FR': {'countryName': 'France', 'phoneCode': '+33', 'phoneLength': 9},
  'GA': {'countryName': 'Gabon', 'phoneCode': '+241', 'phoneLength': 9},
  'GM': {'countryName': 'Gambia', 'phoneCode': '+220', 'phoneLength': 7},
  'GE': {'countryName': 'Georgia', 'phoneCode': '+995', 'phoneLength': 9},
  'DE': {'countryName': 'Germany', 'phoneCode': '+49', 'phoneLength': 10},
  'GH': {'countryName': 'Ghana', 'phoneCode': '+233', 'phoneLength': 10},
  'GR': {'countryName': 'Greece', 'phoneCode': '+30', 'phoneLength': 10},
  'GD': {'countryName': 'Grenada', 'phoneCode': '+1-473', 'phoneLength': 7},
  'GT': {'countryName': 'Guatemala', 'phoneCode': '+502', 'phoneLength': 8},
  'GN': {'countryName': 'Guinea', 'phoneCode': '+224', 'phoneLength': 9},
  'GW': {'countryName': 'Guinea-Bissau', 'phoneCode': '+245', 'phoneLength': 7},
  'GY': {'countryName': 'Guyana', 'phoneCode': '+592', 'phoneLength': 7},
  'HT': {'countryName': 'Haiti', 'phoneCode': '+509', 'phoneLength': 8},
  'HN': {'countryName': 'Honduras', 'phoneCode': '+504', 'phoneLength': 8},
  'HK': {'countryName': 'Hong Kong', 'phoneCode': '+852', 'phoneLength': 8},
  'HU': {'countryName': 'Hungary', 'phoneCode': '+36', 'phoneLength': 9},
  'IS': {'countryName': 'Iceland', 'phoneCode': '+354', 'phoneLength': 7},
  'IN': {'countryName': 'India', 'phoneCode': '+91', 'phoneLength': 10},
  'ID': {'countryName': 'Indonesia', 'phoneCode': '+62', 'phoneLength': 10},
  'IR': {'countryName': 'Iran', 'phoneCode': '+98', 'phoneLength': 10},
  'IQ': {'countryName': 'Iraq', 'phoneCode': '+964', 'phoneLength': 10},
  'IE': {'countryName': 'Ireland', 'phoneCode': '+353', 'phoneLength': 9},
  'IL': {'countryName': 'Israel', 'phoneCode': '+972', 'phoneLength': 9},
  'IT': {'countryName': 'Italy', 'phoneCode': '+39', 'phoneLength': 10},
  'JM': {'countryName': 'Jamaica', 'phoneCode': '+1-876', 'phoneLength': 7},
  'JP': {'countryName': 'Japan', 'phoneCode': '+81', 'phoneLength': 10},
  'JO': {'countryName': 'Jordan', 'phoneCode': '+962', 'phoneLength': 9},
  'KZ': {'countryName': 'Kazakhstan', 'phoneCode': '+7', 'phoneLength': 10},
  'KE': {'countryName': 'Kenya', 'phoneCode': '+254', 'phoneLength': 10},
  'KI': {'countryName': 'Kiribati', 'phoneCode': '+686', 'phoneLength': 8},
  'KP': {'countryName': 'North Korea', 'phoneCode': '+850', 'phoneLength': 8},
  'KR': {'countryName': 'South Korea', 'phoneCode': '+82', 'phoneLength': 10},
  'KW': {'countryName': 'Kuwait', 'phoneCode': '+965', 'phoneLength': 8},
  'KG': {'countryName': 'Kyrgyzstan', 'phoneCode': '+996', 'phoneLength': 9},
  'LA': {'countryName': 'Laos', 'phoneCode': '+856', 'phoneLength': 9},
  'LV': {'countryName': 'Latvia', 'phoneCode': '+371', 'phoneLength': 8},
  'LB': {'countryName': 'Lebanon', 'phoneCode': '+961', 'phoneLength': 8},
  'LS': {'countryName': 'Lesotho', 'phoneCode': '+266', 'phoneLength': 8},
  'LR': {'countryName': 'Liberia', 'phoneCode': '+231', 'phoneLength': 7},
  'LY': {'countryName': 'Libya', 'phoneCode': '+218', 'phoneLength': 9},
  'LI': {'countryName': 'Liechtenstein', 'phoneCode': '+423', 'phoneLength': 7},
  'LT': {'countryName': 'Lithuania', 'phoneCode': '+370', 'phoneLength': 8},
  'LU': {'countryName': 'Luxembourg', 'phoneCode': '+352', 'phoneLength': 9},
  'MG': {'countryName': 'Madagascar', 'phoneCode': '+261', 'phoneLength': 9},
  'MW': {'countryName': 'Malawi', 'phoneCode': '+265', 'phoneLength': 9},
  'MY': {'countryName': 'Malaysia', 'phoneCode': '+60', 'phoneLength': 10},
  'MV': {'countryName': 'Maldives', 'phoneCode': '+960', 'phoneLength': 7},
  'ML': {'countryName': 'Mali', 'phoneCode': '+223', 'phoneLength': 8},
  'MT': {'countryName': 'Malta', 'phoneCode': '+356', 'phoneLength': 8},
  'MH': {
    'countryName': 'Marshall Islands',
    'phoneCode': '+692',
    'phoneLength': 7,
  },
  'MR': {'countryName': 'Mauritania', 'phoneCode': '+222', 'phoneLength': 8},
  'MU': {'countryName': 'Mauritius', 'phoneCode': '+230', 'phoneLength': 8},
  'MX': {'countryName': 'Mexico', 'phoneCode': '+52', 'phoneLength': 10},
  'FM': {'countryName': 'Micronesia', 'phoneCode': '+691', 'phoneLength': 7},
  'MD': {'countryName': 'Moldova', 'phoneCode': '+373', 'phoneLength': 8},
  'MC': {'countryName': 'Monaco', 'phoneCode': '+377', 'phoneLength': 9},
  'MN': {'countryName': 'Mongolia', 'phoneCode': '+976', 'phoneLength': 8},
  'ME': {'countryName': 'Montenegro', 'phoneCode': '+382', 'phoneLength': 8},
  'MA': {'countryName': 'Morocco', 'phoneCode': '+212', 'phoneLength': 9},
  'MZ': {'countryName': 'Mozambique', 'phoneCode': '+258', 'phoneLength': 9},
  'MM': {'countryName': 'Myanmar', 'phoneCode': '+95', 'phoneLength': 9},
  'NA': {'countryName': 'Namibia', 'phoneCode': '+264', 'phoneLength': 9},
  'NR': {'countryName': 'Nauru', 'phoneCode': '+674', 'phoneLength': 7},
  'NP': {'countryName': 'Nepal', 'phoneCode': '+977', 'phoneLength': 10},
  'NL': {'countryName': 'Netherlands', 'phoneCode': '+31', 'phoneLength': 9},
  'NZ': {'countryName': 'New Zealand', 'phoneCode': '+64', 'phoneLength': 9},
  'NI': {'countryName': 'Nicaragua', 'phoneCode': '+505', 'phoneLength': 8},
  'NE': {'countryName': 'Niger', 'phoneCode': '+227', 'phoneLength': 8},
  'NG': {'countryName': 'Nigeria', 'phoneCode': '+234', 'phoneLength': 10},
  'NO': {'countryName': 'Norway', 'phoneCode': '+47', 'phoneLength': 8},
  'OM': {'countryName': 'Oman', 'phoneCode': '+968', 'phoneLength': 8},
  'PK': {'countryName': 'Pakistan', 'phoneCode': '+92', 'phoneLength': 10},
  'PW': {'countryName': 'Palau', 'phoneCode': '+680', 'phoneLength': 7},
  'PA': {'countryName': 'Panama', 'phoneCode': '+507', 'phoneLength': 8},
  'PG': {
    'countryName': 'Papua New Guinea',
    'phoneCode': '+675',
    'phoneLength': 8,
  },
  'PY': {'countryName': 'Paraguay', 'phoneCode': '+595', 'phoneLength': 9},
  'PE': {'countryName': 'Peru', 'phoneCode': '+51', 'phoneLength': 9},
  'PH': {'countryName': 'Philippines', 'phoneCode': '+63', 'phoneLength': 10},
  'PL': {'countryName': 'Poland', 'phoneCode': '+48', 'phoneLength': 9},
  'PT': {'countryName': 'Portugal', 'phoneCode': '+351', 'phoneLength': 9},
  'QA': {'countryName': 'Qatar', 'phoneCode': '+974', 'phoneLength': 8},
  'RO': {'countryName': 'Romania', 'phoneCode': '+40', 'phoneLength': 9},
  'RU': {'countryName': 'Russia', 'phoneCode': '+7', 'phoneLength': 10},
  'RW': {'countryName': 'Rwanda', 'phoneCode': '+250', 'phoneLength': 9},
  'KN': {
    'countryName': 'Saint Kitts and Nevis',
    'phoneCode': '+1-869',
    'phoneLength': 7,
  },
  'LC': {'countryName': 'Saint Lucia', 'phoneCode': '+1-758', 'phoneLength': 7},
  'VC': {
    'countryName': 'Saint Vincent and the Grenadines',
    'phoneCode': '+1-784',
    'phoneLength': 7,
  },
  'WS': {'countryName': 'Samoa', 'phoneCode': '+685', 'phoneLength': 7},
  'SM': {'countryName': 'San Marino', 'phoneCode': '+378', 'phoneLength': 9},
  'ST': {
    'countryName': 'Sao Tome and Principe',
    'phoneCode': '+239',
    'phoneLength': 7,
  },
  'SA': {'countryName': 'Saudi Arabia', 'phoneCode': '+966', 'phoneLength': 9},
  'SN': {'countryName': 'Senegal', 'phoneCode': '+221', 'phoneLength': 9},
  'RS': {'countryName': 'Serbia', 'phoneCode': '+381', 'phoneLength': 9},
  'SC': {'countryName': 'Seychelles', 'phoneCode': '+248', 'phoneLength': 7},
  'SL': {'countryName': 'Sierra Leone', 'phoneCode': '+232', 'phoneLength': 8},
  'SG': {'countryName': 'Singapore', 'phoneCode': '+65', 'phoneLength': 8},
  'SK': {'countryName': 'Slovakia', 'phoneCode': '+421', 'phoneLength': 9},
  'SI': {'countryName': 'Slovenia', 'phoneCode': '+386', 'phoneLength': 9},
  'SB': {
    'countryName': 'Solomon Islands',
    'phoneCode': '+677',
    'phoneLength': 7,
  },
  'SO': {'countryName': 'Somalia', 'phoneCode': '+252', 'phoneLength': 9},
  'ZA': {'countryName': 'South Africa', 'phoneCode': '+27', 'phoneLength': 9},
  'ES': {'countryName': 'Spain', 'phoneCode': '+34', 'phoneLength': 9},
  'LK': {'countryName': 'Sri Lanka', 'phoneCode': '+94', 'phoneLength': 9},
  'SD': {'countryName': 'Sudan', 'phoneCode': '+249', 'phoneLength': 9},
  'SR': {'countryName': 'Suriname', 'phoneCode': '+597', 'phoneLength': 7},
  'SE': {'countryName': 'Sweden', 'phoneCode': '+46', 'phoneLength': 9},
  'CH': {'countryName': 'Switzerland', 'phoneCode': '+41', 'phoneLength': 9},
  'SY': {'countryName': 'Syria', 'phoneCode': '+963', 'phoneLength': 9},
  'AE': {
    'countryName': 'United Arab Emirates',
    'phoneCode': '+971',
    'phoneLength': 9,
  },
  'EH': {
    'countryName': 'Western Sahara',
    'phoneCode': '+212',
    'phoneLength': 9,
  },
  'FJ': {'countryName': 'Fiji', 'phoneCode': '+679', 'phoneLength': 7},
  'GB': {
    'countryName': 'United Kingdom',
    'phoneCode': '+44',
    'phoneLength': 10,
  },
  'SS': {'countryName': 'South Sudan', 'phoneCode': '+211', 'phoneLength': 9},
  'TG': {'countryName': 'Togo', 'phoneCode': '+228', 'phoneLength': 8},
  'TH': {'countryName': 'Thailand', 'phoneCode': '+66', 'phoneLength': 9},
  'TJ': {'countryName': 'Tajikistan', 'phoneCode': '+992', 'phoneLength': 9},
  'TL': {'countryName': 'Timor-Leste', 'phoneCode': '+670', 'phoneLength': 7},
  'TM': {'countryName': 'Turkmenistan', 'phoneCode': '+993', 'phoneLength': 8},
  'TN': {'countryName': 'Tunisia', 'phoneCode': '+216', 'phoneLength': 8},
  'TO': {'countryName': 'Tonga', 'phoneCode': '+676', 'phoneLength': 5},
  'TR': {'countryName': 'Turkey', 'phoneCode': '+90', 'phoneLength': 10},
  'TT': {
    'countryName': 'Trinidad and Tobago',
    'phoneCode': '+1-868',
    'phoneLength': 7,
  },
  'TV': {'countryName': 'Tuvalu', 'phoneCode': '+688', 'phoneLength': 5},
  'TZ': {'countryName': 'Tanzania', 'phoneCode': '+255', 'phoneLength': 9},
  'UA': {'countryName': 'Ukraine', 'phoneCode': '+380', 'phoneLength': 9},
  'UG': {'countryName': 'Uganda', 'phoneCode': '+256', 'phoneLength': 9},
  'US': {'countryName': 'United States', 'phoneCode': '+1', 'phoneLength': 10},
  'UY': {'countryName': 'Uruguay', 'phoneCode': '+598', 'phoneLength': 9},
  'UZ': {'countryName': 'Uzbekistan', 'phoneCode': '+998', 'phoneLength': 9},
  'VE': {'countryName': 'Venezuela', 'phoneCode': '+58', 'phoneLength': 10},
  'VN': {'countryName': 'Vietnam', 'phoneCode': '+84', 'phoneLength': 9},
  'VU': {'countryName': 'Vanuatu', 'phoneCode': '+678', 'phoneLength': 7},
  'XK': {'countryName': 'Kosovo', 'phoneCode': '+383', 'phoneLength': 9},
  'YE': {'countryName': 'Yemen', 'phoneCode': '+967', 'phoneLength': 9},
  'ZM': {'countryName': 'Zambia', 'phoneCode': '+260', 'phoneLength': 9},
  'ZW': {'countryName': 'Zimbabwe', 'phoneCode': '+263', 'phoneLength': 9},*/
};

// resuable
Map<String, dynamic>? getCountryDetails(String countryCode) {
  return countryPhoneCodeMapping[countryCode];
}

Future<void> showCountrySelectorBottomSheet({
  required BuildContext context,
  required Function(
    String countryName,
    int phoneLength,
    String flatIcon,
    String phoneCode,
  )
  onCountrySelected,
}) async {
  TextEditingController searchController = TextEditingController();
  ValueNotifier<List<MapEntry<String, Map<String, dynamic>>>>
  filteredCountries = ValueNotifier(countryPhoneCodeMapping.entries.toList());

  void filterCountries(String query) {
    filteredCountries.value =
        countryPhoneCodeMapping.entries.where((entry) {
          final countryName = entry.value['countryName'].toLowerCase();
          final phoneCode = entry.value['phoneCode'].toLowerCase();
          final searchQuery = query.toLowerCase();
          return countryName.contains(searchQuery) ||
              phoneCode.contains(searchQuery);
        }).toList();
  }

  String getFlagEmoji(String countryCode) {
    return countryCode
        .toUpperCase()
        .codeUnits
        .map((e) => String.fromCharCode(e + 0x1F1E6 - 65))
        .join();
  }

  showModalBottomSheet(
    context: context,
    isScrollControlled: true,
    backgroundColor: AppColor().kAppWhiteColor,
    builder: (context) {
      return Container(
        padding: const EdgeInsets.all(16.0),
        height: MediaQuery.of(context).size.height * 0.8,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            customText('Select a Country', 16.0, context),
            const SizedBox(height: 10),
            TextField(
              controller: searchController,
              style: TextStyle(color: AppColor().kAppBlackColor),
              decoration: InputDecoration(
                hintText: 'Search by country name or code',
                prefixIcon: Icon(Icons.search),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12.0),
                ),
              ),
              onChanged: filterCountries,
            ),
            const SizedBox(height: 10),
            Expanded(
              child: ValueListenableBuilder<
                List<MapEntry<String, Map<String, dynamic>>>
              >(
                valueListenable: filteredCountries,
                builder: (context, countries, child) {
                  return ListView.builder(
                    itemCount: countries.length,
                    itemBuilder: (context, index) {
                      final entry = countries[index];
                      final countryCode = entry.key;
                      final details = entry.value;

                      return ListTile(
                        leading: Text(
                          getFlagEmoji(countryCode), // Add the flag here
                          style: TextStyle(
                            fontSize: 24,
                          ), // Adjust size for better visuals
                        ),
                        title: customText(
                          details['countryName'],
                          16.0,
                          context,
                          fontWeight: FontWeight.w600,
                        ),
                        subtitle: customText(
                          details['phoneCode'],
                          12.0,
                          context,
                          fontWeight: FontWeight.w400,
                        ),
                        // Text(details['phoneCode']),
                        onTap: () {
                          onCountrySelected(
                            details['countryName'],
                            details['phoneLength'],
                            getFlagEmoji(countryCode),
                            details['phoneCode'], // flag icon
                          );
                          Navigator.pop(context);
                        },
                      );
                    },
                  );
                },
              ),
            ),
          ],
        ),
      );
    },
  );
}
